const colors = {
  white: "#fff",
  blue: "#0095ff",
  "head-color": "#596689",
  "header-text-color": "#97b0d6"
};

export default {
  "white-color": colors.white,
  "blue-color": colors.blue,
  "blue-dark-color": "#295e9f",
  "up-color": "#12b886",
  "down-color": "#fa5252",
  "warning-color": "#dea959",
  "info-color": "#a4afb9",
  "text-default-color": "#e1e7ef",
  "color-gray": "#728bb9",
  "text-dropdown-color": "#c6d8f3",
  "bg-color": "#0e182b",
  "bg-loading-color": "rgba(31, 37, 66, 0.9)",
  "bg-card-color": "#182640",
  "bg-head-color": "#213150",
  "bg-card-head-color": "#213150",
  "bg-downdown-color": "#25344e",
  "bg-downdown-border-color": "#3b4d6b",
  "border-color": "#314363",
  "ul-color": "#e9effb",
  "input-color": colors.white,
  "value-color": colors.white,
  "icon-color": "#7482a0",
  "selected-color": colors.white,
  "selected-bg-color": "#2e3f5f",
  "selected-blue-color": colors.blue,
  "selected-border-color": colors.blue,
  "row-hover-bg-color": "rgba(46, 55, 83, 0.4)",
  "input-placeholder-color": colors["head-color"],
  "header-text-color": colors["header-text-color"],
  "footer-text-color": colors["header-text-color"],
  "disabled-color": "#7a869a",
  "sort-color": "#3c4a68",
  "user-border-color": "#515a6e",
  "user-border-selected-color": "#5470a9",
  "user-icon-selected-color": "#295e9f",
  //Mobile Custom
  "mobile-icon-color": "#a5abb5",
  "mobile-placeholder-color": "#a5abb5"
};
